name: Build and Upload Lambda

on:
  push:
    branches:
      - main
    paths:
      - "app_services/lambda_etl/**"

jobs:
  build-lambda:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write   # para OIDC (melhor prática)

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Build Lambda package
        run: |
          cd app_services/lambda_etl
          zip -r handler.zip .

      - name: Upload to S3
        run: |
          aws s3 cp app_services/lambda_etl/handler.zip \
            s3://mlops-pipeline-passosmagicos-artifacts/lambda_etl/handler.zip